import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full">
          <Navbar />
        </nav>
      <ToastContainer
      position="bottom-right"
      autoClose={3000}
      limit={3}
      theme="dark"

      />
        {children}
      </body>
    </html>
  );
}
