import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MealsLayout({ children }) {

  return (
    <>
      <nav className="w-full">
        <Navbar />
      </nav>
      {children}
    </>
  );
}

{/* <html lang="en" className={`${playfair_display.variable} ${montserrat.variable} ${pacifico.variable} ${playfair_display.className}`}>
<body className="bg-black">
<ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem
      disableTransitionOnChange
    > */}


// </ThemeProvider>
//       <Toaster />
//       </body>
//     </html>


{/* <ToastContainer
position="bottom-right"
autoClose={3000}
limit={1}
theme="dark"

/> */}