import { Inter, Playfair_Display, Montserrat, Pacifico } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

const playfair_display = Playfair_Display({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-playfair-display'
})

const montserrat= Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat'
})

const pacifico= Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair_display.variable} ${montserrat.variable} ${pacifico.variable}`}>
      <body className={playfair_display.className}>
        <nav className="w-full">
          <Navbar />
        </nav>
      <ToastContainer
      position="bottom-right"
      autoClose={3000}
      limit={3}
      theme="dark"

      />
        {children}
      </body>
    </html>
  );
}
